import { Tool } from "@langchain/core/tools";
import { lighthouseService } from "../services/lighthouse";
import { uploadToImgbb } from "../services/imgbb";
import { getLLM } from "../services/llm";
import { logger } from "../services/logger";
import { config } from "../config/env";

// LangChain Tool wraps native tool-call args as { input: "<json-string>" }.
// This helper unwraps that envelope so _call always gets the real params.
function parseToolInput(raw: string): Record<string, unknown> {
  const outer = JSON.parse(raw);
  if (typeof outer.input === "string") {
    try {
      return JSON.parse(outer.input);
    } catch {
      // outer.input is a plain string, not JSON — keep outer so callers can read outer.input
      return outer;
    }
  }
  return outer;
}

export class GenerateImageTool extends Tool {
  name = "generate_image";
  description =
    "Generate an image using Gemini image generation. Input: JSON with 'prompt' describing the image to generate. Returns the hosted image URL ready for display.";

  private gemini = getLLM("gemini-image-gen");

  async _call(input: string): Promise<string> {
    let prompt = input;
    try {
      const parsed = parseToolInput(input);
      prompt = (parsed.prompt as string) || (parsed.input as string) || input;
    } catch {}

    logger.info("LLM", "[Yasmin] generate_image: invoking Gemini image generation", { model: "gemini-2.0-flash-exp", promptPreview: prompt.slice(0, 150) });
    const response = await this.gemini.invoke([
      {
        role: "user",
        content: prompt,
      },
    ]);

    // Extract base64 image data from Gemini's multimodal response
    const parts = Array.isArray(response.content) ? response.content : [];
    const imagePart = parts.find(
      (p: unknown) => (p as { type: string }).type === "image_url"
    ) as { type: string; image_url: { url: string } } | undefined;

    const base64 = imagePart?.image_url?.url?.replace(/^data:image\/\w+;base64,/, "");

    // Extract any text description returned alongside the image
    const textPart = parts.find(
      (p: unknown) => (p as { type: string }).type === "text"
    ) as { type: string; text: string } | undefined;
    const description = textPart?.text ?? (typeof response.content === "string" ? response.content : "");

    logger.info("LLM", "[Yasmin] generate_image: Gemini responded", { hasImage: !!base64, descriptionPreview: description.slice(0, 200) });

    // Upload image to imgbb for public hosting (5 min expiry)
    let imgbbUrl: string | undefined;
    if (base64 && config.IMGBB_API_KEY) {
      try {
        imgbbUrl = await uploadToImgbb(base64);
      } catch (err) {
        logger.warn("IMGBB", "[Yasmin] generate_image: imgbb upload failed, falling back to Lighthouse", { error: String(err) });
      }
    } else if (!config.IMGBB_API_KEY) {
      logger.warn("IMGBB", "[Yasmin] generate_image: IMGBB_API_KEY not set, skipping imgbb upload");
    }

    // Upload metadata to Lighthouse for on-chain reference
    const cid = await lighthouseService.upload(
      JSON.stringify({ prompt, description, imgbbUrl, generated_by: "Yasmin via gemini-2.0-flash-exp" })
    );
    logger.info("IPFS", "[Yasmin] generate_image: metadata uploaded to Lighthouse", { cid, imgbbUrl, promptPreview: prompt.slice(0, 100) });

    const displayUrl = imgbbUrl ?? lighthouseService.getGatewayUrl(cid);

    return JSON.stringify({
      prompt,
      description,
      imageCID: cid,
      url: displayUrl,
      lighthouseUrl: lighthouseService.getGatewayUrl(cid),
      note: "Image generated by Gemini. Use imageCID with create_nft_metadata to complete NFT.",
    });
  }
}

export class CreateNFTMetadataTool extends Tool {
  name = "create_nft_metadata";
  description =
    "Create NFT metadata JSON. Input: JSON with 'name', 'description', 'imageCID' fields. Returns metadata CID.";

  async _call(input: string): Promise<string> {
    let params: Record<string, unknown> = {};
    try {
      params = parseToolInput(input);
    } catch {
      return JSON.stringify({ error: "Invalid JSON input for create_nft_metadata" });
    }
    const name = params.name as string | undefined;
    const description = params.description as string | undefined;
    const imageCID = (params.imageCID ?? params.image_cid ?? params.cid) as string | undefined;
    const attributes = Array.isArray(params.attributes) ? params.attributes : [];
    const metadata = {
      name,
      description,
      image: imageCID ? `ipfs://${imageCID}` : undefined,
      attributes,
      created_by: "Yasmin - Vantage Labs",
    };
    const cid = await lighthouseService.upload(JSON.stringify(metadata));
    logger.info("IPFS", "[Yasmin] create_nft_metadata: metadata uploaded", { cid, name, url: lighthouseService.getGatewayUrl(cid) });
    return JSON.stringify({ cid, metadata, url: lighthouseService.getGatewayUrl(cid) });
  }
}

export class UploadToFilecoinTool extends Tool {
  name = "upload_to_filecoin";
  description =
    "Upload content to Filecoin via Lighthouse. Input: string content or JSON. Returns CID.";

  async _call(input: string): Promise<string> {
    const cid = await lighthouseService.upload(input);
    logger.info("IPFS", "[Yasmin] upload_to_filecoin: content uploaded", { cid, url: lighthouseService.getGatewayUrl(cid) });
    return JSON.stringify({ cid, url: lighthouseService.getGatewayUrl(cid) });
  }
}

export class CreateTweetTool extends Tool {
  name = "create_tweet";
  description =
    "Generate a marketing tweet. Input: JSON with 'context' field. Returns tweet text.";

  async _call(input: string): Promise<string> {
    let context = input;
    try {
      context = JSON.parse(input).context || input;
    } catch {}
    return JSON.stringify({
      tweet: `🚀 Exciting news from Vantage Labs! ${context} #Web3 #DeFi #Flow #Filecoin #DAA`,
      charCount: 280,
    });
  }
}
