import { StructuredTool } from "@langchain/core/tools";
import { z } from "zod";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { lighthouseService } from "../services/lighthouse";
import { uploadToImgbb } from "../services/imgbb";
import { logger } from "../services/logger";
import { config } from "../config/env";

const IMAGE_GEN_MODEL = "gemini-2.0-flash-preview-image-generation";

export class GenerateImageTool extends StructuredTool {
  name = "generate_image";
  description =
    "Generate an image using Gemini. Provide a detailed visual prompt describing what the image should look like.";
  schema = z.object({
    prompt: z.string().describe("Detailed description of the image to generate"),
  });

  async _call({ prompt }: { prompt: string }): Promise<string> {
    logger.info("LLM", "[Yasmin] generate_image: invoking Gemini image generation", { model: IMAGE_GEN_MODEL, promptPreview: prompt.slice(0, 150) });

    // Use @google/generative-ai directly with v1alpha (required for image generation preview)
    const genAI = new GoogleGenerativeAI(config.GEMINI_API_KEY);
    const model = genAI.getGenerativeModel(
      {
        model: IMAGE_GEN_MODEL,
        // @ts-expect-error responseModalities is valid for image generation models
        generationConfig: { responseModalities: ["IMAGE", "TEXT"] },
      },
      { apiVersion: "v1alpha" }
    );

    const result = await model.generateContent(prompt);
    const parts = result.response.candidates?.[0]?.content?.parts ?? [];

    // Extract base64 image bytes and text description from response parts
    const imagePart = parts.find((p) => p.inlineData?.data);
    const textPart = parts.find((p) => p.text);
    const base64 = imagePart?.inlineData?.data;
    const description = textPart?.text ?? "";

    logger.info("LLM", "[Yasmin] generate_image: Gemini responded", { hasImage: !!base64, descriptionPreview: description.slice(0, 200) });

    // Upload image to imgbb for public hosting (5 min expiry)
    let imgbbUrl: string | undefined;
    if (base64 && config.IMGBB_API_KEY) {
      try {
        imgbbUrl = await uploadToImgbb(base64);
      } catch (err) {
        logger.warn("IMGBB", "[Yasmin] generate_image: imgbb upload failed, falling back to Lighthouse", { error: String(err) });
      }
    } else if (!config.IMGBB_API_KEY) {
      logger.warn("IMGBB", "[Yasmin] generate_image: IMGBB_API_KEY not set, skipping imgbb upload");
    }

    // Upload metadata to Lighthouse for on-chain reference
    const cid = await lighthouseService.upload(
      JSON.stringify({ prompt, description, imgbbUrl, generated_by: `Yasmin via ${IMAGE_GEN_MODEL}` })
    );
    logger.info("IPFS", "[Yasmin] generate_image: metadata uploaded to Lighthouse", { cid, imgbbUrl, promptPreview: prompt.slice(0, 100) });

    const displayUrl = imgbbUrl ?? lighthouseService.getGatewayUrl(cid);

    return JSON.stringify({
      prompt,
      description,
      imageCID: cid,
      url: displayUrl,
      lighthouseUrl: lighthouseService.getGatewayUrl(cid),
      note: "Image generated by Gemini. Use imageCID with create_nft_metadata to complete NFT.",
    });
  }
}

export class CreateNFTMetadataTool extends StructuredTool {
  name = "create_nft_metadata";
  description = "Create NFT metadata JSON and upload to Filecoin via Lighthouse. Returns the metadata CID.";
  schema = z.object({
    name: z.string().describe("Name of the NFT"),
    description: z.string().describe("Description of the NFT"),
    imageCID: z.string().describe("IPFS CID of the NFT image"),
    attributes: z.array(z.record(z.string(), z.unknown())).optional().describe("Optional NFT attributes array"),
  });

  async _call({ name, description, imageCID, attributes = [] }: {
    name: string;
    description: string;
    imageCID: string;
    attributes?: Record<string, unknown>[];
  }): Promise<string> {
    const metadata = {
      name,
      description,
      image: `ipfs://${imageCID}`,
      attributes,
      created_by: "Yasmin - Vantage Labs",
    };
    const cid = await lighthouseService.upload(JSON.stringify(metadata));
    logger.info("IPFS", "[Yasmin] create_nft_metadata: metadata uploaded", { cid, name, url: lighthouseService.getGatewayUrl(cid) });
    return JSON.stringify({ cid, metadata, url: lighthouseService.getGatewayUrl(cid) });
  }
}

export class UploadToFilecoinTool extends StructuredTool {
  name = "upload_to_filecoin";
  description = "Upload arbitrary content to Filecoin via Lighthouse. Returns the CID.";
  schema = z.object({
    content: z.string().describe("Content to upload (string or JSON)"),
  });

  async _call({ content }: { content: string }): Promise<string> {
    const cid = await lighthouseService.upload(content);
    logger.info("IPFS", "[Yasmin] upload_to_filecoin: content uploaded", { cid, url: lighthouseService.getGatewayUrl(cid) });
    return JSON.stringify({ cid, url: lighthouseService.getGatewayUrl(cid) });
  }
}

export class CreateTweetTool extends StructuredTool {
  name = "create_tweet";
  description = "Generate a marketing tweet for Vantage Labs.";
  schema = z.object({
    context: z.string().describe("Context or topic for the tweet"),
  });

  async _call({ context }: { context: string }): Promise<string> {
    return JSON.stringify({
      tweet: `🚀 Exciting news from Vantage Labs! ${context} #Web3 #DeFi #Flow #Filecoin #DAA`,
      charCount: 280,
    });
  }
}
